//  javascript output module

// c / c++/

/*
int 
chrt
float
double
boolean
number
object
array
andefined
null
*/

// Datatypes / primitive Datatypes and non-primitive Datatypes

// premitive datatypes / immutable

/*
string
number
boolean
null
undefined
symbol
*/

// non-primitive Datatypes / mutable

/*
array
object
*/

// var greek = 'skillqode learning institute!' // sring datatypes

// console.log(greek);
// console.warn(greek);
// document.write(greek);
// alert(greek);

// DOM document object model (html document file nodes handle)
// document.getElementById('demo').innerHTML = greek;

// string methods
// string.prototypes

// string write method

{
    var names = "Raju"

    var str1 = 'This is \'string\' "Method" ${names}!'
    var str2 = "This is \"string\" 'Method' ${names}!"
    var str3 = `This is string Method ${names}!`
   
    console.log(str1);
    console.log(str2);
    console.log(str3);
    
    var str4 = new String('thish is string Method')

    console.log(str4);
}

// string prototypes
// string string.concat() method

//  The concat() method of string values concatenats the string arguments to this string and returns a new string.

// concat()
// concat(str1)
// concat(str1, str2)
// concat(str1, str2, /* ..., */ strN)

{
    // let str = "This is Frist String "
    // let str2 = "This is Second String "
    // let str3 = "This is Third String "

    // let Multistr = str.concat(str2,str3)

    // console.log(Multistr);

}


